
services:
  server:
    build:
      context: .
      dockerfile: dockerfile
  proxy:
    image: nginx:latest
    ports:
      - "8087:85"
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
    depends_on:
      - server

networks:
  default:
    driver: bridge
    name: webnet

